### This jupyter notebook contains contents of the lesson "Arithmetic operators in Series and Dataframe"

**Author : Umidjon Sattorov. Machine Learning engineer**

In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.23.2 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
%pip install numpy

Requirement already satisfied: numpy in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.3.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

In [4]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [5]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [6]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [5]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [8]:
s1.add(s2, fill_value = 0)

a    5.2
c    1.1
d    3.4
e    0.0
f    4.0
g    3.1
dtype: float64

Task : Create two series, one of which should contain integers and other one should contain boolean variables. Multiply first series to second one and return the result.

Task : Create two series, one of which should contain the names of people and the other one should contain surnames of them. Add them together.

In [13]:
s1 = pd.Series([ 88, 7, 12, 5, 100, 4.2, 3.0, 9.9], index=[ "q","s","w","z","u","d","l","k"])
s2 = pd.Series([-2.1, 3.6, 10.5, 4.1 , 13.4 ,100, 56, 3.0 ], index=["a", "c", "e", "f", "g", "p", "o", "u"])

In [14]:
s1*s2

a      NaN
c      NaN
d      NaN
e      NaN
f      NaN
g      NaN
k      NaN
l      NaN
o      NaN
p      NaN
q      NaN
s      NaN
u    300.0
w      NaN
z      NaN
dtype: float64

____

In [16]:
s1.multiply(s2, fill_value = 9)

a    -18.9
c     32.4
d     37.8
e     94.5
f     36.9
g    120.6
k     89.1
l     27.0
o    504.0
p    900.0
q    792.0
s     63.0
u    300.0
w    108.0
z     45.0
dtype: float64

In [ ]:
s1.subtract()
s1.div()
s1.divmod()

In [18]:
data = {
    "gold" : [1900, 2000, 2100, 1950, 1800],
    "silver" : [500, 520, 530, 490, 400],
    "platinum" : [4000, 4200, 4100, 4099, 5000]
}
df = pd.DataFrame(data)
df

   gold  silver  platinum
0  1900     500      4000
1  2000     520      4200
2  2100     530      4100
3  1950     490      4099
4  1800     400      5000

In [24]:
df1 = pd.DataFrame(
    np.arange(9.).reshape(3, 3),
    columns = list('bcd'),
    index = ['Apple', 'Pomegranate', 'Grapes'] 
)

df2 = pd.DataFrame(
    np.arange(12.).reshape(4, 3),
    columns = list('abc'),
    index = ['Apple', 'Pomegranate', 'Melon', 'Fig']
)
df1

               b    c    d
Apple        0.0  1.0  2.0
Pomegranate  3.0  4.0  5.0
Grapes       6.0  7.0  8.0

In [8]:
df2

               a     b     c
Apple        0.0   1.0   2.0
Pomegranate  3.0   4.0   5.0
Melon        6.0   7.0   8.0
Fig          9.0  10.0  11.0

In [9]:
df1+df2

              a    b    c   d
Apple       NaN  1.0  3.0 NaN
Fig         NaN  NaN  NaN NaN
Grapes      NaN  NaN  NaN NaN
Melon       NaN  NaN  NaN NaN
Pomegranate NaN  7.0  9.0 NaN

In [10]:
df1-df2

              a    b    c   d
Apple       NaN -1.0 -1.0 NaN
Fig         NaN  NaN  NaN NaN
Grapes      NaN  NaN  NaN NaN
Melon       NaN  NaN  NaN NaN
Pomegranate NaN -1.0 -1.0 NaN

In [25]:
# add() function
df1.add(df2, fill_value=0)

               a     b     c    d
Apple        0.0   1.0   3.0  2.0
Fig          9.0  10.0  11.0  NaN
Grapes       NaN   6.0   7.0  8.0
Melon        6.0   7.0   8.0  NaN
Pomegranate  3.0   7.0   9.0  5.0

In [12]:
# add() function with fill_value
df1.add(df2, fill_value = 0)

               a     b     c    d
Apple        0.0   1.0   3.0  2.0
Fig          9.0  10.0  11.0  NaN
Grapes       NaN   6.0   7.0  8.0
Melon        6.0   7.0   8.0  NaN
Pomegranate  3.0   7.0   9.0  5.0

Other Arithmetic Operations
add, radd – Addition (+)

* sub, rsub – Subtraction (-)

* div, rdiv – Division (/)

* floordiv, rfloordiv – Floor division (//)

* mul, rmul – Multiplication (*)

* pow, rpow – Exponentiation (**)

All of the operations above support the fill_value parameter.

____

In [33]:
df1.sub(df2,fill_value = 0)

               a     b     c    d
Apple        0.0  -1.0  -1.0  2.0
Fig         -9.0 -10.0 -11.0  NaN
Grapes       NaN   6.0   7.0  8.0
Melon       -6.0  -7.0  -8.0  NaN
Pomegranate -3.0  -1.0  -1.0  5.0

In [41]:
df1.div(df2,fill_value = 0)

               a     b    c    d
Apple        NaN  0.00  0.5  inf
Fig          0.0  0.00  0.0  NaN
Grapes       NaN   inf  inf  inf
Melon        0.0  0.00  0.0  NaN
Pomegranate  0.0  0.75  0.8  inf

In [40]:
df1.floordiv(df2,fill_value = 0)

               a    b    c    d
Apple        NaN  0.0  0.0  inf
Fig          0.0  0.0  0.0  NaN
Grapes       NaN  inf  inf  inf
Melon        0.0  0.0  0.0  NaN
Pomegranate  0.0  0.0  0.0  inf

In [39]:
df1.mul(df2,fill_value = 1)

               a     b     c    d
Apple        0.0   0.0   2.0  2.0
Fig          9.0  10.0  11.0  NaN
Grapes       NaN   6.0   7.0  8.0
Melon        6.0   7.0   8.0  NaN
Pomegranate  3.0  12.0  20.0  5.0

In [ ]:
df1.pow(df2,fill_value = )

               a     b       c    d
Apple        1.0   0.0     1.0  1.0
Fig          0.0   0.0     0.0  NaN
Grapes       NaN   1.0     1.0  1.0
Melon        0.0   0.0     0.0  NaN
Pomegranate  0.0  81.0  1024.0  1.0